# Generated by Django 5.2.1 on 2025-06-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_task_completed_remove_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
