# Generated by Django 5.2.1 on 2025-06-29 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_performancerating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performancerating',
            name='remarks',
        ),
    ]
