# Generated by Django 5.2.1 on 2025-07-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_performancerating_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
