# Generated by Django 5.2.1 on 2025-07-13 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_employee_resume_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performancerating',
            old_name='created_at',
            new_name='date_rated',
        ),
        migrations.RemoveField(
            model_name='performancerating',
            name='period',
        ),
        migrations.AddField(
            model_name='performancerating',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='performancerating',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee'),
        ),
        migrations.AlterField(
            model_name='performancerating',
            name='rated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
