# Generated by Django 5.2.1 on 2025-07-21 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_created_at_performancerating_date_rated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttritionPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.FloatField()),
                ('prediction', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
        ),
    ]
