# Generated by Django 5.2.1 on 2025-07-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_employee_age_employee_business_travel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='business_travel',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='distance_from_home',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='environment_satisfaction',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='job_satisfaction',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='num_companies_worked',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='over_time',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='percent_salary_hike',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='relationship_satisfaction',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='stock_option_level',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='total_working_years',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='training_times_last_year',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='work_life_balance',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='years_at_company',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='years_in_current_role',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='years_since_last_promotion',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='years_with_curr_manager',
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='monthly_income',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
