# Generated by Django 5.2.1 on 2025-07-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_employee_skills_project_required_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='required_skills',
        ),
        migrations.AddField(
            model_name='project',
            name='domain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
