# Generated by Django 5.2.1 on 2025-07-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_project_required_skills_project_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='domain_matched_tasks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='total_tasks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
