# Generated by Django 5.2.1 on 2025-07-24 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_employee_domain_matched_tasks_employee_total_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='domain_matched_tasks',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='total_tasks',
        ),
    ]
