# Generated by Django 5.2.1 on 2025-07-24 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_project_criticality_project_deadline_leaverequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
    ]
