# Generated by Django 5.2.1 on 2025-08-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_customuser_role_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('HR', 'HR'), ('TL', 'Team Lead'), ('EMP', 'Employee'), ('Guest', 'Guest')], default='Guest', max_length=20),
        ),
    ]
