# Generated by Django 5.2.1 on 2025-09-08 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_project_team_lead_manager_project_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='manager',
        ),
        migrations.AlterField(
            model_name='project',
            name='team_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teamlead'),
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
